name: 'Dependency Review'
on:
  pull_request:
  merge_group:
permissions: read-all
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
        with:
          base-ref: ${{ github.base_ref || github.event.merge_group.base_ref }}
          head-ref: ${{ github.head_ref || github.event.merge_group.head_ref }}
