name: "Dependency Review"
on:
  pull_request:
  merge_group:
permissions: read-all
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
        with:
          base-ref: ${{ github.base_ref || github.event.merge_group.base_ref }}
          head-ref: ${{ github.head_ref || github.event.merge_group.head_ref }}
