name: 'Dependency Review'
on:
  pull_request:
  merge_group:
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/dependency-review-action@c74b580d73376b7750d3d2a50bfb8adc2c937507 # v3.1.5
        with:
          base-ref: ${{ github.base_ref || github.event.merge_group.base_ref }}
          head-ref: ${{ github.head_ref || github.event.merge_group.head_ref }}
