---
name: fail-notify
on:
  workflow_run:
    workflows:
      - Add to Task List
      - Dependency Review
      - fix-fail-notify
      - format-json-yml
      - github-actions-cache-cleaner
      - super-linter
      - update-gitleaks
    types:
      - completed
jobs:
  fail-notify:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Get slack payload
        id: get_slack_payload
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/scripts/fail_notify/fail_notify/get_slack_payload.js`)
            return script({context})
      - uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          channel-id: ${{secrets.SLACK_CHANNEL_ID}}
          payload: ${{steps.get_slack_payload.outputs.result}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
