---
name: format
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  merge_group:
permissions: read-all
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: stable
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: go mod tidy
      - uses: dev-hato/actions-diff-pr-management@128afc4203b4e391e03868be91c987b2ddba7ea5 # v1.1.12
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: format
          pr-title-prefix: Format修正
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
