---
name: super-linter
on:
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
  statuses: write
jobs:
  super-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: super-linter/super-linter/slim@56576d491db07c7236b445ab09991ca49d12b0c6 # v6.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .
          # Go modulesを使っているため、こちらはfalseにする
          VALIDATE_GO: false
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
