---
name: update-gitleaks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  merge_group:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
      - uses: dev-hato/actions-update-gitleaks@29f460ba4165cad4df14a67123951818d112e8ab # v0.0.78
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
